name: Variables y Secretos

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimiendo variables y secretos
        run: |
          echo "La variable es ${{vars.mi_variable}}"
          echo "El secreto es ${{secrets.CONNECTION_STRING}}"

        # 
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Correr codigo de JS
        run: node main.js
        env:
          VARIABLE_CENTRALIZADA: ${{vars.mi_variable}}
